apiVersion: sql.arcdata.microsoft.com/v4
kind: SqlManagedInstance
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"sql.arcdata.microsoft.com/v2","kind":"SqlManagedInstance","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"sqlmi"},"name":"sql-gp-1","namespace":"arc"},"spec":{"backup":{"retentionPeriodInDays":7},"dev":true,"forceHA":"true","licenseType":"LicenseIncluded","replicas":1,"scheduling":{"default":{"resources":{"limits":{"cpu":"1","memory":"2Gi"},"requests":{"cpu":"1","memory":"2Gi"}}}},"security":{"adminLoginSecret":"sql-login-secret"},"services":{"primary":{"port":31433,"type":"LoadBalancer"}},"storage":{"backups":{"volumes":[{"className":"azurefile","size":"1Gi"}]},"data":{"volumes":[{"className":"managed-premium","size":"1Gi"}]},"datalogs":{"volumes":[{"className":"managed-premium","size":"1Gi"}]},"logs":{"volumes":[{"className":"managed-premium","size":"1Gi"}]}},"tier":"GeneralPurpose"}}
  creationTimestamp: "2022-03-21T19:26:11Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: sqlmi
    management.azure.com/resourceProvider: Microsoft.AzureArcData
  name: sql-gp-1
  namespace: arc
  resourceVersion: "304139"
  uid: 4b0130fb-72fc-403a-8323-b6c98f6f9d01
spec:
  backup:
    retentionPeriodInDays: 7
  dev: true
  forceHA: "true"
  licenseType: LicenseIncluded
  readableSecondaries: 0
  replicas: 1
  scheduling:
    default:
      resources:
        limits:
          cpu: "1"
          memory: 2Gi
        requests:
          cpu: "1"
          memory: 2Gi
  security:
    adminLoginSecret: sql-login-secret
  services:
    primary:
      port: 31433
      type: LoadBalancer
  settings:
    collation: SQL_Latin1_General_CP1_CI_AS
    language:
      lcid: 1033
    network:
      forceencryption: 0
      tlsciphers: ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384
      tlsprotocols: "1.2"
    sqlagent:
      enabled: false
    timezone: UTC
  storage:
    backups:
      volumes:
      - className: azurefile
        size: 1Gi
    data:
      volumes:
      - accessMode: ReadWriteOnce
        className: managed-premium
        size: 1Gi
    datalogs:
      volumes:
      - className: managed-premium
        size: 1Gi
    logs:
      volumes:
      - accessMode: ReadWriteOnce
        className: managed-premium
        size: 1Gi
  tier: GeneralPurpose
status:
  lastUpdateTime: "2022-03-21T20:08:50.741610Z"
  observedGeneration: 1
  state: Creating
