apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sqlmi
spec:
  destination:
    name: ''
    namespace: arc
    server: 'https://kubernetes.default.svc'
  source:
    path: kubernetes/sqlmi
    repoURL: 'https://github.com/mdrakiburrahman/arc-data-benchmark.git'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
