apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weavescope
spec:
  destination:
    name: ''
    namespace: weave
    server: 'https://kubernetes.default.svc'
  source:
    path: kubernetes/weavescope
    repoURL: 'https://github.com/mdrakiburrahman/arc-data-benchmark.git'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
